#######################################################
# THIS DOCKER COMPOSE IS INTENDED FOR LOCAL TEST ONLY.#
# DO NOT USE IN PRODUCTION ENVIRONMENT.               #
#######################################################
version: '3'

services:
  app-add:
    build:
      context: app-add
    expose:
      - "5001"
    ports:
      - "5001:5001"
    environment:
      PORT: 5001

  app-diff:
    depends_on:
      - app-add
    build:
      context: app-diff
    expose:
      - "5002"
    ports:
      - "5002:5002"
    environment:
      PORT: 5002

  app-mult:
    depends_on:
      - app-add
    build:
      context: app-mult
    expose:
      - "5003"
    ports:
      - "5003:5003"
    environment:
      PORT: 5003

  app-diff:
    depends_on:
      - app-diff
    build:
      context: app-div
    expose:
      - "5004"
    ports:
      - "5004:5004"
    environment:
      PORT: 5004
