apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-deployment
  labels:
    app: add
spec:
  replicas: 2
  selector:
    matchLabels:
      app: add
  template:
    metadata:
      labels:
        app: add
    spec:
      containers:
        - name: app-add
          image: phonxvzf/app-add
          ports:
            - containerPort: 5001
          env:
            - name: "PORT"
              value: "5001"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diff-deployment
  labels:
    app: diff
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diff
  template:
    metadata:
      labels:
        app: diff
    spec:
      containers:
        - name: app-diff
          image: phonxvzf/app-diff
          ports:
            - containerPort: 5002
          env:
            - name: "PORT"
              value: "5002"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mult-deployment
  labels:
    app: mult
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mult
  template:
    metadata:
      labels:
        app: mult
    spec:
      containers:
        - name: app-mult
          image: phonxvzf/app-mult
          ports:
            - containerPort: 5003
          env:
            - name: "PORT"
              value: "5003"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: div-deployment
  labels:
    app: div
spec:
  replicas: 2
  selector:
    matchLabels:
      app: div
  template:
    metadata:
      labels:
        app: div
    spec:
      containers:
        - name: app-div
          image: phonxvzf/app-div
          ports:
            - containerPort: 5004
          env:
            - name: "PORT"
              value: "5004"
      restartPolicy: Always
---
