apiVersion: v1
kind: Service
metadata:
  name: app-add
  labels:
    service: add
spec:
  selector:
    app: add
  ports:
    - port: 5001
      nodePort: 30000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: app-diff
  labels:
    service: diff
spec:
  selector:
    app: diff
  ports:
    - port: 5002
      nodePort: 30001
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: app-mult
  labels:
    service: mult
spec:
  selector:
    app: mult
  ports:
    - port: 5003
      nodePort: 30002
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: app-div
  labels:
    service: div
spec:
  selector:
    app: div
  ports:
    - port: 5004
      nodePort: 30003
  type: NodePort
