apiVersion: v1
kind: Service
metadata:
  name: add-service
  labels:
    app: add
spec:
  selector:
    app: add
  ports:
    - protocol: TCP
      port: 5001
      # targetPort: 5001
      nodePort: 30000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: diff-service
  labels:
    app: diff
spec:
  selector:
    app: diff
  ports:
    - protocol: TCP
      port: 5001
      # targetPort: 5001
      nodePort: 30001
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mul-service
  labels:
    app: mul
spec:
  selector:
    app: mul
  ports:
    - protocol: TCP
      port: 5001
      # targetPort: 5001
      nodePort: 30002
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: div-service
  labels:
    app: div
spec:
  selector:
    app: div
  ports:
    - protocol: TCP
      port: 5001
      # targetPort: 5001
      nodePort: 30003
  type: NodePort
